### ISSUE TITLE
TypeError: Invalid background RGBA argument

### ISSUE THREAD

**Issue by simon2x** [AlexTS1980/awesmspaceshooter#1]
``` python
Traceback (most recent call last):
  File "D:\awesmspaceshooter-master\src\main_package_spaceshooter\Main.py", line 716, in <module>
    main()
  File "D:\awesmspaceshooter-master\src\main_package_spaceshooter\Main.py", line 357, in main
    main_screen.blit(title_font_object.render(main_title.upper(), 1, (0, 255, 0), None), (
TypeError: Invalid background RGBA argument
```

Hi, just downloaded and tried to run it unmodified with python 2.7 and received the error above
thanks.

**Comment by AlexTS1980** [comment]
hi there, I've never run it in pythnon2, only python3

**Comment by simon2x** [comment]
Hi, thanks. Got it running fine under python 3.4. I completed the game also :)

**Comment by AlexTS1980** [comment]
OK great)
